name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: setup Node 12
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - run: npm install
      - run: |
          npm config set "//npm.pkg.github.com/:_authToken" "${{ secrets.GITHUB_TOKEN }}"
          npm config set "@alaatm:registry" "https://npm.pkg.github.com/"
          npm config set always-auth true
      - run: npm publish
